# Declare ndarray

importing numpy as np

In [1]:
import numpy as np

Create ndarray using regular Python lists

This is a 1D ndarray or rank 1 array

In [2]:
x = np.array([1,2,3,4,5])

In [4]:
print('x = ', x)

x =  [1 2 3 4 5]


In [5]:
print()
print('x dimensions: ', x.shape)
print('x is an object of type: ', type(x))
print('The elements in x are of type: ', x.dtype)


x dimensions:  (5,)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  int32


In [7]:
#We create a rank 1 ndarray that only contains strings
y = np.array(['Hello','World'])

#Print y
print()
print('y = ',y)
print()

# We print information about y
print('y has dimension: ',y.shape)
print('y is an object of type: ',type(y))
print('The elements in y are of type: ',y.dtype)


y =  ['Hello' 'World']

y has dimension:  (2,)
y is an object of type:  <class 'numpy.ndarray'>
The elements in y are of type:  <U5


To see what happens if you mix data type for ndarrays

In [9]:
# We create a rank 1 ndarray that only contains strings and integers
z = np.array(['Hello',1, 2])

# We print z
print()
print('z = ',z)
print()

# We print information about z
print('z has dimension: ',z.shape)
print('z is an object of type: ',type(z))
print('The elements in z are of type: ',z.dtype)


z =  ['Hello' '1' '2']

z has dimension:  (3,)
z is an object of type:  <class 'numpy.ndarray'>
The elements in z are of type:  <U5


Now creating rank 2 arrays

In [10]:
# We create a rank 2 ndarray that only contains integers
r = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

# We print r
print()
print('r = ',r)
print()

# We print information about r
print('r has dimension: ', r.shape)
print('r has a total of ', r.size, ' elements')
print('r is an object of type: ',type(r))
print('The elements in r are of type: ',r.dtype)


r =  [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

r has dimension:  (4, 3)
r has a total of  12  elements
r is an object of type:  <class 'numpy.ndarray'>
The elements in r are of type:  int32


Specifying the data type for the ndarray

In [12]:
# We create a rank 1 ndarray of floats but set the dtype to int32
t = np.array([1.5, 2.2, 3.4, 4.3, 5.6], dtype = np.int32)

# We print t
print()
print('t = ', t)
print()

# We print the dtype t
print('The elements in t are of type: ', t.dtype)


t =  [1 2 3 4 5]

The elements in t are of type:  int32


Saving ndarray to be used later

In [13]:
# We save x into the current directory as
np.save('my_array', x)

loading the saved array into a variable

In [14]:
# We load the saved array from our current directory into a variable q
q = np.load('my_array.npy')

# We print q
print()
print('q = ', q)
print()

# We print information about the ndarray we loaded
print('q is an object of type: ', type(q))
print('The elements in q are of type: ', q.dtype)


q =  [1 2 3 4 5]

q is an object of type:  <class 'numpy.ndarray'>
The elements in q are of type:  int32


# Built-in Functions

Creating ndarray with a specified shape that is full of zeros

In [16]:
# We create a 3 x 4 ndarray full of zeros.
x = np.zeros((3,4))

# We print x
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

x has dimension:  (3, 4)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  float64


Creating ndarray of ones

In [18]:
# We create a 3 x 2 ndarray full of ones.
x = np.ones((3,2))

# We print x
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [[1. 1.]
 [1. 1.]
 [1. 1.]]

x has dimension:  (3, 2)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  float64


Create ndarray of constant value

In [19]:
# We create a 2 x 3 ndarray full of fives
x = np.full((2,3),5)

# We print x
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [[5 5 5]
 [5 5 5]]

x has dimension:  (2, 3)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  int32


Create N x N ndarray corresponding to the Identity matrix

In [20]:
# We create a 5 x 5 Identity matrix.
x = np.eye(5)

# We print x
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

x has dimension:  (5, 5)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  float64


Create a Diagonal matrix

In [21]:
# Create a 4 x 4 diagonal matrix that contains the numbers 10, 20, 30, and 50
# on its main diagonal
x = np.diag([10,20,30,50])

# We print
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]

x has dimension:  (4, 4)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  int32


Create rank 1 ndarray using arange from 0 to N-1

In [23]:
# We create a rank 1 ndarray that has sequential integers from 0 to 9
x = np.arange(10)

# We print the ndarray
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [0 1 2 3 4 5 6 7 8 9]

x has dimension:  (10,)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  int32


Create a rank 1 ndarray with arange and start and stop value

In [24]:
# We create a rank 1 ndarray that has sequential integers from 4 to 9
x = np.arange(4,10)

# We print the ndarray
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [4 5 6 7 8 9]

x has dimension:  (6,)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  int32


Create rank 1 ndarray with step value

In [25]:
# We create rank 1 ndarray that has evenly spaced integers from 1 to 13 in steps of 3
x = np.arange(1,14,3)

# We print the ndarray
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [ 1  4  7 10 13]

x has dimension:  (5,)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  int32


Create ndarray that include the the start and end value and evenly spaced. Needs to be called with minimum of 2 arguments

In [27]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25.
x = np.linspace(0, 25, 10)

# We print ndarray
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

x has dimension:  (10,)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  float64


Create linspace() ndarray excluding the end value

In [28]:
# We create a rank 1 ndarray that has 10 integers evenly spaced between 0 and 25, with 25 excluded.
x = np.linspace(0, 25, 10, endpoint=False)

# We print ndarray
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]

x has dimension:  (10,)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  float64


Changing a rank 1 ndarray to rank 2 ndarray

In [30]:
# We create a rank 1 ndarray with sequential integers from 0 to 19
x = np.arange(20)

# We print x
print()
print("Original x = ", x)
print()

# We reshape x into a 4 x 5 ndarray
x = np.reshape(x, (4, 5))

# We print the reshaped x
print()
print("Reshaped x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


Original x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


Reshaped x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

x has dimension:  (4, 5)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  int32


Applying some functions as methods with dot notation 

In [32]:
# We create a rank 1 ndarray with sequential integers from 0 to 19 and reshape it to a 4 x 5 array
x = np.arange(20).reshape(4,5)

# We print x
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

x has dimension:  (4, 5)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  int32


Create ndarrays using random

In [33]:
# We create a 3 x 3 ndarray with random floats in the half-open interval [0.0, 1.0)
x = np.random.random((3,3))

# We print x
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [[0.69416595 0.4842607  0.46265373]
 [0.53364906 0.59985852 0.25222945]
 [0.7542771  0.64090784 0.935457  ]]

x has dimension:  (3, 3)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  float64


In [34]:
# We create a 3 x 2 ndarray with random integers in the half-open inteval [4, 15)
x = np.random.randint(4,15,size=(3,2))

# We print x
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)


x = 
 [[ 5  4]
 [12 12]
 [ 5 10]]

x has dimension:  (3, 2)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  int32


In [36]:
# We create a 1000 x 1000 ndarray of random floats drawn from normal (Gaussian) distribution
# with a mean of zero and a standard deviation of 0.1.
x = np.random.normal(0, 0.1, size=(1000,1000))

# We print x
print()
print("x = \n", x)
print()

# We print information about x
print("x has dimension: ",x.shape)
print("x is an object of type: ", type(x))
print("The elements in x are of type: ", x.dtype)
print("The elements in x have a mean of: ", x.mean())
print("The maximum value in x is: ",x.max())
print("The minimum value in x is: ",x.min())
print("x has ", (x < 0).sum(), " negative numbers")
print("x has ", (x > 0).sum(), "positive numbers")


x = 
 [[ 0.15465236 -0.03702177  0.14751011 ... -0.04954508  0.17177945
  -0.04219985]
 [-0.05247782 -0.01660921  0.20578362 ...  0.0995572  -0.12781023
  -0.09048748]
 [ 0.08385701  0.03496921  0.041879   ...  0.12815127  0.1161466
   0.05742066]
 ...
 [ 0.01585508 -0.02128012  0.01972747 ... -0.09435382  0.02163721
  -0.21488638]
 [-0.08036494  0.09242109 -0.14372407 ... -0.0140139  -0.1567584
  -0.06245101]
 [ 0.05714521  0.20894729 -0.11303502 ...  0.14396734  0.03373328
  -0.13557734]]

x has dimension:  (1000, 1000)
x is an object of type:  <class 'numpy.ndarray'>
The elements in x are of type:  float64
The elements in x have a mean of:  -6.382636231066508e-05
The maximum value in x is:  0.5008051108100746
The minimum value in x is:  -0.4694994609241822
x has  500366  negative numbers
x has  499634 positive numbers
